
name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: '0 0 * * *' # roda todo dia
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Generate 3D profile contributions
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
